name: Deploy React Portfolio to Hostinger

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use Node.js version 16 or later

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React project for production
      - name: Build React project
        run: npm run build

      # Step 5: Deploy files to Hostinger using FTP
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./build # The directory of your build files
          server-dir: /public_html # The directory on your Hostinger server
